#!/bin/sh
set -e

. /usr/share/debconf/confmodule

[ -n "${DEBUG}" ] && set -o xtrace

echo "INFO: dropfile.postrm as '$1' ($2)"

case "$1" in
    remove)

        # nothing to do

        ;;

    purge)

        if [ -e /usr/share/debconf/confmodule ]; then
            . /usr/share/debconf/confmodule
            db_purge
        fi

        # Here, we should get rid of things within /var/lib/dropfile/ except
        # this is dangerous since it might delete data ... should we do it?
        #rm -rf /var/lib/dropfile/

        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "dropfile.postrm called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

db_stop
exit 0
